sudo: required
language: ruby
rvm:
  - 2.5.1
cache: bundler
before_install:
  - travis_retry sudo apt-get update 
  - sudo bash -c "curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | bash"
env:
  global:
    - JAVA_OPTS="java.awt.headless=true"
script:
  - plantuml -testdot
  - make clean all publish
